### ISSUE TITLE
Validate version against semver rules and custom rules

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/semver-action#14]
As a developer responsible for maintaining the quality and consistency of software releases, I want to utilize a command-line tool that validates version numbers against semantic versioning rules and additional custom rules. This tool will be integrated into our automated release workflows to ensure that versions are assigned correctly before initiating any release process.

The app should be available as both a standalone Docker container and a GitHub Action. This enhances its usability and integration within our development ecosystem and allows developers to seamlessly incorporate version validation into their preferred workflows

### Acceptance Criteria
- [x] Should validate that the version follows semantic versioning rules
- [x] Should validate that every version starts with a leading `v`
- [x] Should detect invalid pre-release versions: We only allow alpha, beta and RC (e.g. `v0.1.0-alpha.0)
- [x] Should detect any metadata (metadata is not valid)
- [ ] Should be greater than another version
    - :no_entry_sign: BLOCKER: https://github.com/hashicorp/go-version/issues/130
- [ ] Should #4

### Tasks
- [x] Lint `*.feature` files
- [x] Translate the user story into executable specifications
- [x] Test the service with cucumber and lots of values
- [x] Test the `cmd.Execute()` with 2 values (one success, one failure) and check, that the return code is 0 for the first test and 1 for the second test.
    - :no_entry_sign: BLOCKER: https://stackoverflow.com/questions/76859593/unit-test-to-how-i-test-for-exit-codes-in-go-without-exiting-the-testcase-when-t
    - [x] Command: root
    - [x] Command: validate
- [x] Prepare blog post or howto article (see below)
    - [x] Provide test case example
    - [x] Update: Have functions return an exit code or set a var, call `os.Exit(0)` and `os.Exit(1)` only from `main()`
- [ ] #21

### See also
- Look into https://github.com/sommerfeld-io/semver-action/issues/3 for information on how to count versions

**Comment by sebastian-sommerfeld-io** [comment]
Look into https://github.com/sommerfeld-io/semver-action/issues/3 for information on how to count versions

**Comment by sebastian-sommerfeld-io** [comment]
### Write "How to test Go code that returns exit code other that 0"
#### Synopsis
- Devide into two parts
    - *1*: An "unstable" part that contains the actual logic and indicates success/failure with bool return value or better indicates success/failure by returning nil/error. This part is implemented as a function and changes every time the business logic changes (because it contains the business logic). 
    - *2*:  A stable part that calls the function and handles `os.Exit(0)` and `os.Exit(1)`
- Test these parts separately
    - *1*: Test the unstable part with lots of different data combinations for success and failure
    - *2*: Test stable part with two data combinations (one for success and then test for `os.Exit(0)` and one for failue and then test for `os.Exit(1)`)

#### Blog content
...

### Tasks
- [ ] Test the run function with cucumberand lots of values
- [ ] Test the cmd.Execute() with 2 values (one success, one failure) and check, that the return code is 0 fpr the first test and 1 for the second test.
- [ ] Prepare blog post or howto article
