### ISSUE TITLE
Try to combine DevContainer and Gitpod by using the same Base Image

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/semver-action#6]

**Comment by sebastian-sommerfeld-io** [comment]
### Support Gitpod.io or Github Codespaces

As a developer, I want to enable support for gitpod.io in this repository. By doing so, I aim to enhance the development workflow and provide an improved collaborative environment for contributors.

Enabling support for gitpod.io will allow contributors to quickly and effortlessly set up a development environment with all the necessary dependencies and configurations pre-installed. This streamlined setup process will save time and effort, enabling contributors to focus on the task at hand and reducing the barrier to entry for new developers.

#### Todo

- [ ] Decide whether to use gitpod or GitHub Codespaces … Codespaces seem to leverage devcontaimers … this might mean that I could use the same devcontainer locally in vscode … this would be a plus
    - [ ] Write ADR -> maybe put in dev-environment-confit because this is a fundamental decision with effect on every repo! Link to adr in this repo because this is the trigger?

#### Read
- [ ] https://blog.okikio.dev/github-codespaces-vs-gitpod-choosing-the-best-online-code-editor
- [ ] https://www.gitpod.io/vs/github-codespaces
- [ ] https://www.freecodecamp.org/news/github-codespaces-vs-gitpod-cloud-based-dev-environments/
